export const strings = {
  WELCOME: 'Welcome!',
  HOW_TO_USE_THIS_APP: 'How to use this app:',
  NO_1: '1. Login',
  NO_2: "2. go to 'Song Lookup'",
  NO_3: 'Enter a song title.',
  NO_4: 'Get the price, lyrics, and a similar artist.',
  YOU_ARE_DONE: "You're done!",
  LOGIN: 'Login',
  DONT_HAVE_AN_ACCOUNT: "Don't have an account?",
  SIGN_UP: 'Sign Up',
  HOME: 'Home',
  SONG_LOOK_UP: 'Song LookUp',
  USERNAME: 'Username',
  PASSWORD: 'Password',
  RE_TYPE_PASSWORD: 'Re-type Password',
  ALREADY_HAVE_AN_ACCOUNT: 'Already have an account?',
  SONG_TITLE: 'Song Title',
  SONG_ARTIST: 'Song Artist',
  GO: 'Go!',
  ITUNES_PRICE: 'iTunes Price',
  SONG_LYRICS: 'Song Lyrics',
  SIMILAR_ARTIST: 'Similar Artist',
  WE_COUDNT_FIND_INFORMATION: "We couldn't find information about that song...",
  LOGOUT: 'Log Out',
  SONG_NAME: 'Song Name',
  ARTIST_NAME: 'Artist Name',
  RELEASE_DATE: 'Release Date',
  PRICE: 'Price',
  COUNTRY: 'Country',
  CURRENCY: 'Currency',
  COLLECTION_NAME: 'Collection Name',
  NO_INTERNET_CONNECTION: 'NO INTERNET CONNECTION',
  PLEASE_CHECK_YOUR_INTERNET_CONNECTION:
    'Please check your internet connection and try again',
  WTEASER: 'wTeaser',
  WURL: 'wUrl',
  INFORMATION: 'Information received based on the song goes here.',
};
